### PR TITLE
Add action to push images to GitHub container repository 

### PR DESCRIPTION
**Pull request by rob-luke**
This will add a docker image to the GitHub registery. Then users can run it simply by running (no need to download git repo etc)....

```bash
docker run ghcr.io/mne-tools/mne-python/base command....
```

I registered this one as base. Later down the track I imagine a situation where you can call `ghcr.io/mne-tools/mne-python/base` Or `ghcr.io/mne-tools/mne-python/3d` Or `ghcr.io/mne-tools/mne-python/jupyter` Etc 

It will also add a new version each time a tag is made. So users can call:

```bash
docker run ghcr.io/mne-tools/mne-python/base:v0.1.7
```

### CODE REVIEW

**Comment by rob-luke** [comment]
@agramfort @larsoner @bloyl @SherazKhan could you please review

**Comment by bloyl** [comment]
Seems like the right idea. I'm assuming the plan is to Tag this repo based on MNE-releases?

I have 2 comments
1) Is it possible to also push images to docker hub
2) I usually only see a single nesting depth on image names. I'm not sure if this is required or just convention.
What do people think of `mne-tools/mne-python:0.23.0` for the base image and `mne-tools/mne-python-viz:0.23.0`. I'm assuming we are gong to tag based on mne-python versions?

**Comment by rob-luke** [comment]
> Is it possible to also push images to docker hub

I don't see the advantage of this. The GH registry works just the same, and has the benefit that you can find the image right on the same page as the code. I guess people are just accustomed to looking on docker hub. But happy to review a Pr if you implement it. I don't see any issue with two registries as long as the process is automated so that they stay aligned.

> What do people think of mne-tools/mne-python:0.23.0 for the base image and mne-tools/mne-python-viz:0.23.0

I hate shortenings like viz. it makes things harder to search for. And assumes people know what they are doing. Can we use the full word - visualisation? (Preferably with correct spelling, but I doubt I'll win that argument 😉) Or plot, or something else meaningful?

> I'm assuming we are gong to tag based on mne-python versions?

Makes sense to me. I personally need access to main builds too, so how about:

- mne-tools/mne-python:0.23.0
- mne-tools/mne-python-plot:0.23.0
- mne-tools/mne-python-notebook:0.23.0

- mne-tools/mne-python:latest
- mne-tools/mne-python-plot:latest
- mne-tools/mne-python-notebook:latest

And we use latest to refer to main build (latest is the common docker term)? And I will add a notebook version, similar to how you did the viz one in a seperate PR. I.e. _notebook_ will just inherit from _plot_ which inherits from _base_.

Once we agree on a set of names (I think we are close). Then we just wait for #7 to get merged. And then I will update this PR accordingly.

**Comment by bloyl** [comment]
I'm fine with the `mne-python-plot` I'll switch it in #7 to consistent and if people want to change it they can in another PR.

I've only seen people build off images from dockerhub. For instance I think `FROM mnetools/mne-python` will use a local image and then if its not found pull `:latest` from dockerhub. I don't know how to accomplish that using github registry. I also don't know how to search GH registry. so its hard for me to test. I note again that I am not an expert in any of this :)

I don't follow what you want the `latest` tag to contain. Do you want it to have the dev versions of this repo (this is what you have now) or do you want it to have the dev version of mne-python. I think the 1st is more in line with the way I've seen it other places. Doing the second would need modifications of the docker file and would probably be hard to keep up to date (you'd need to trigger the build here by changes in the other repo)

**Comment by rob-luke** [comment]
> I don't follow what you want the latest tag to contain. Do you want it to have the dev versions of this repo (this is what you have now) or do you want it to have the dev version of mne-python

Sorry I wasn't clear. I want it to contain the dev version of MNE-python.

I can see how this is confusing though. And I have seen it done both ways that you describe. What do you think of this alternative... Adding the following images (I'm happy to do it in a follow up PR, leave the implementation details till then, but keen to get your thoughts here)

- mne-tools/mne-python-dev:latest
- mne-tools/mne-python-dev-plot:latest
- mne-tools/mne-python-dev-notebook:latest

So dev will refer to the fact MNE-Python is main branch at time of image build. And latest will refer to the most recent code from _this_ repository. Would that be clearer?

**Comment by rob-luke** [comment]
Thanks for the input @bloyl. I will add the dev and Jupyter images in a seperate PR.

And we should also ensure these images are pushed to docker hub too if that helps you.

**Pull request merged**
