### PR TITLE
Bump package versions to match MNE-Python testing

### PR DESCRIPTION
**Pull request by rob-luke**
Values taken from https://github.com/mne-tools/mne-python/runs/3080025790#step:8:32

### CODE REVIEW

**Comment by agramfort** [comment]
@rob-luke I am curious about your usecase here? how do you use docker in
the lab?

>

**Comment by rob-luke** [comment]
Hi @agramfort,

I have been using docker for the following:

1. I work with many people who are better at the clinical side of research, rather than the technical. I find that when I set up a python environment for them it often gets corrupted (incompatible package versions, missing packages, etc), even though they (claim) not to have touched anything. So I have been spending much of my days fixing python and anaconda environments. Lately I have been trying these docker environments instead, and so far have found them to be easier to fix when an issue arrises, I simply run `docker rmi image` to remove the existing image, then `docker run ...` and a clean jupyter environment is ready to go. I have an opinionated docker image that I have built on top of the official MNE one here https://github.com/rob-luke/mne-nirs-docker that describes how to mount a directory etc.
2. I have used the mne-nirs-docker image (built on top of this repo) to work with the binder links at the bottom of the MNE-NIRS example pages.
3. I have started building BIDS-Apps style programs that I call fNIRS-Apps, these are built on top of docker images. See https://github.com/rob-luke/fnirs-apps-sourcedata2bids

I personally use a local python install. But for new users I think the ease of use of these images is a real benefit. I have only been using these docker images for use case 1 for a few weeks, but its already saved me hours.

**Comment by agramfort** [comment]
very interesting ! thanks for sharing

**Comment by rob-luke** [comment]
My pleasure @agramfort, thanks for the support.

As an FYI, I think this repo is now largely functional for my purposes. I will continue to make changes, but at a slower pace. Now that it works the changes will be more optimisations of image size, documentation, etc.

**Pull request merged**
