### PR TITLE
Add GitHub action to build docker image

### PR DESCRIPTION
**Pull request by rob-luke**
Does not push, I thought it best to try and get it to build first.

### CODE REVIEW

**Comment by agramfort** [comment]
ok now it's running @rob-luke

**Comment by rob-luke** [comment]
Thanks. I am trying a few different GitHub Actions out. I will push here whatever I settle on.

**Review by agramfort — APPROVED** [review]

**Comment by agramfort** [comment]
@SherazKhan I let you merge if happy.

thx @rob-luke !

**Comment by rob-luke** [comment]
Thanks @agramfort. Two questions before you merge

1. I had to disable the notebook to get this tick green. Do you want me to add the notebook back in before merging. I won't be able to make it work, but is it better to have the CI included but failing?
2. You can use the CI to push the package to The GitHub package service. If so, you would need to enable the service as described [here](https://docs.github.com/en/packages/working-with-a-github-packages-registry/enabling-improved-container-support-with-the-container-registry). But that would be better suited to a follow up PR I think

**Comment by rob-luke** [comment]
For an example of a github released package see https://github.com/rob-luke/fnirs-apps-scalp-coupling-index/pkgs/container/fnirs-apps-scalp-coupling-index%2Fapp

**Comment by agramfort** [comment]
@rob-luke I let you coordinate with @SherazKhan who uses this for his research. I don't use docker :)

**Review by bloyl — APPROVED** [review]
With the huge Caveat that I don't know Github actions (and barely any docker)....

This looks good to me.

I'd suggest that in a later PR we add some basic testing.
1) calling mne sys_info
2) call some variant that tests plotting output

I'm unclear how to check those results so getting actions running and then adding tests seems to be the way to go.

**Comment by larsoner** [comment]
For a simple test I would create a simple 3D scene like:
```
import mne
import numpy as np
size = (600, 600)
renderer = mne.viz.backends.renderer.create_3d_figure(bgcolor='w', size=size, scene=False)
mne.viz.set_3d_backend('pyvista')
renderer.sphere((0, 0, 0), 'k', 1, resolution=1000)
renderer.plotter.camera.enable_parallel_projection(True)
renderer.figure.plotter.camera.SetParallelScale(1)
renderer.show()
data = (renderer.screenshot() / 255.).mean(-1)  # colors
renderer.close()
want = np.ones(size)
dists = np.sqrt(
    np.linspace(-1, 1, size[0])[:, np.newaxis] ** 2 +
    np.linspace(-1, 1, size[1]) ** 2)
want = (dists > 0.5).astype(float)
corr = np.corrcoef(want.ravel(), data.ravel())[0, 1]
assert 0.99 <= corr <= 1
```
Screenshot from 2021-06-24 09-38-48

**Comment by rob-luke** [comment]
Thank you all for reviewing.

@larsoner can we add this 3D test in the PR for adding 3D support? #7 I'd like to get the CI up and running to evaluate that PR.

@agramfort @larsoner can we merge this, or best to wait for @SherazKhan?

**Comment by SherazKhan** [comment]
> Thank you all for reviewing.
> 
> @larsoner can we add this 3D test in the PR for adding 3D support? #7 I'd like to get the CI up and running to evaluate that PR.
> 
> @agramfort @larsoner can we merge this, or best to wait for @SherazKhan?

@rob-luke please go ahead with merging

**Comment by agramfort** [comment]
thx @rob-luke @SherazKhan !

**Comment by rob-luke** [comment]
Thanks all

**Pull request merged**
